name: triki
version: 0.0.1
author: Kornel Maczyński <kornel661@gmail.com>
description: Trikipedia web interface.
environment:
  sdk: '>=1.8.5 <2.0.0'
dependencies:
  browser: '^0.10.0+2'
  core_elements: '^0.6.1+2'
  paper_elements: '^0.6.2+2'
  polymer: '^0.16.0+6'
  spa_router:
    path: '/home/kornel/Documents/programowanie/triki/spa-router'
transformers:
- polymer:
    entry_points: web/index.html
